### ISSUE TITLE
Does not recursively find dependencies

### ISSUE THREAD

**Issue by lunelson** [lishid/pug-dependency#1]
I'm finding that if I have `page.pug` extending `app.pug` which extends `base.pug`, which includes `mixins.pug`, if I say `d.find_dependencies('page.pug')` it only gives me `['app.pug']`, when it should actually give me `['app.pug', 'base.pug', 'mixins.pug']`

**Comment by lishid** [comment]
I've made the exact same setup and I find the output to be correct:

```
let dependency = require('pug-dependency');
let d = dependency('pug/**/*.pug');
console.log(d.find_dependencies('pug/page.pug').map(x => x.substring(process.cwd().length)));
```
![image](https://user-images.githubusercontent.com/609710/30983640-06dc5504-a459-11e7-8a18-76542710a8f4.png)
Output

```
[ '\\pug\\app.pug', '\\pug\\base.pug', '\\pug\\mixing.pug' ]
```
